version: "3.8"

services:
  mysql:
    image: mysql:8.0
    cap_add:
      - CAP_SYS_NICE
    container_name: golang_database
    command: "--default-authentication-plugin=mysql_native_password"
    environment:
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "password"
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "godatabase"
    ports:
      - 3306:3306
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
